apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-voting-app
      role: frontend
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app
        role: frontend
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1